apiVersion: v1
kind: Secret

metadata:
  name: kserve-minio-secret
  namespace: user1

  annotations:
    serving.kserve.io/s3-endpoint: "minio-service.kubeflow.svc.cluster.local:9000"
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: "us-east-1"
    serving.kserve.io/s3-useanoncredential: "false"

type: Opaque

stringData:
  AWS_ACCESS_KEY_ID: "minio"
  AWS_SECRET_ACCESS_KEY: "minio123"